#+TITLE: Logitech Keyboard Configuration
#+PROPERTY: header-args :tangle yes

* Super Keybindings
I want to be able to use Super like a leader key when tapped
Each headline represents a key to be pressed after tapping Super
** Q :: Window Switcher
Launches the window switcher
** D :: Discord
Opens Discord
** B :: Brightness
Opens ~BrightnessControl~ GUI *OR* initiates ~BrightnessControl~ layer, where we can manipulate brightness with ~hjkl~
Also look into [[https://github.com/maoserr/redshiftgui][redshiftgui]] to see if we can use this instead. I left it alone because building it requires a library that isn't in the Fedora repos called "[[https://sourceforge.net/projects/iup/files/3.30/Linux%20Libraries/][IUP]]"
*** BrightnessControl Layer
**** H
Rotate active monitor to the left
**** L
Rotate active monitor to the right
**** K
Brightness Up
**** J
Brightness Down
**** Esc | Super
Exit layer
** V :: Volume
Opens volume manager
*** Volume Layer
**** H
Rotate current output left
**** J
Rotate current output right
**** K
Volume up by 5
**** L
Volume down by 5
** T :: Terminal (Scratchpad)
Opens terminal scratchpad
*** Hold
Opens menu with all of the available scratchpads
*** Tap
+Opens most recently opened scratchpad+
We can use ~yakuake~ for this basic functionality
Instead, dedicate this to the *Terminal Layer*?
*** Terminal Layer
**** +Super,+​] :: Next
Next terminal scratchpad (cycle)
**** +Super,+​[ :: Previous
Last terminal scratchpad (cycle)
**** L :: List
Show all open scratchpads and prompt for which one to open
**** V :: Vim
Create a Vim scratchpad that will be deleted immediately after Vim closes
** R :: Run
Run a single command in a small popup window

Have it appear at the top of the screen, and have the window expand down as the output fills

This could be super useful for things like ~remind-in 10m Do something~
*** Layer
**** Super, Esc (in sequence)
Exit layer and close ~run~ window
**** E
Make window taller
*** Notes
**** Keybindings
In the spawned window, bind Ctrl+R to resize the window to the necessary length, Esc/Enter to revert the size

After you press enter "for real", hand the scrollback buffer to ~pee resizing_program.sh less~
Might have to use kitty for this
**** Window Properties
Source: https://www.reddit.com/r/kde/comments/d5ne9s/can_you_have_no_titlebar_and_frame_but_keep_the/
Made a window-specific override for the window class "st-runner" that disabled the title bar
This lets us havae the nice shadow but without the title bar
** P :: Prompt
Opens prompt to open ~rofi~ and launch custom actions by typing
*** thyme
Opens ~rofi~ with list of ~thyme~ files
Choose a date and then view the breakdown for that date
*** incognito
Turns on VPN
Disables ~thyme~

If called a second time, disables both of these
** A :: Agenda
Opens agenda
** O :: Open Preset
*** Tap
Gives you preset-local shortcuts

Automatically show help for it (this is hard to memorize)
Emacs ~which-key~ style help
*** Hold
Opens ~rofi~ with list of available "presets"

If currently in a preset, exit the preset
Currently loaded presets should be at the top!
If you select a preset while another is currently active, disable the old preset

Add support for virtual-desktop-local presets in the future
*** Presets
**** leetcode
***** Left Monitor
1. Open fullscreen terminal
2. ~cd ~/Development/leetcode/problems~
***** Right Monitor
+1. Open firefox+
+2. Navigate to [[https://www.teamblind.com/post/New-Year-Gift---Curated-List-of-Top-75-LeetCode-Questions-to-Save-Your-Time-OaM1orEU][New Year Gift - Curated List of Top 75 LeetCode Questions to Save Your Time]]+
+3.+
0. Open firefox?
   This would be so that when you press enter in emacs, it would open the link in the right firefox window
1. Open ~emacs~
2. Navigate to "problems.org"
3. Select a problem
4. When you press enter, open the link in our firefox window and then close emacs
***** Preset-Local Shortcuts
****** O :: Open Problem List
Opens the ~emacs~ window once again and loops from step #1
** \ :: Local Leader Key
Use this in conjunction with presets to have local preset keybindings
** Super :: Super
Acts as a regular press of Super (hands it to KDE)
* Layer Templates
#+PROPERTY: header-args :tangle no
** Passthrough
#+begin_example kbd
(deflayer layer-name
  _    _    _    _    _    _    _    _    _    _    _    _    _    _
  _    _    _    _    _    _    _    _    _    _    _    _    _    _
  _    _    _    _    _    _    _    _    _    _    _    _    _
  _    _    _    _    _    _    _    _    _    _    _    _                  _
  _    _    _              _              _    _    _                    _   _
                                                                           _
  )
#+end_src
** Inclusive
#+begin_example kbd
(deflayer layer-name
  grv  1    2    3    4    5    6    7    8    9    0    -    =    bspc
  tab  q    w    e    r    t    y    u    i    o    p    [    ]    \
  caps a    s    d    f    g    h    j    k    l    ;    '    ret
  lsft z    x    c    v    b    n    m    ,    .    /    rsft               up
  lctl lmet lalt           spc            ralt rctl                     lft rght
                                                                          down
  )
#+end_src
* Configuration
#+begin_src kbd
(defcfg
  ;; For Linux
  input  (device-file "/dev/input/by-id/usb-Logitech_USB_Receiver-if02-event-kbd")
  output (uinput-sink "Logitech KMonad Output"
                       ;; To understand the importance of the following line, see the section on
                       ;; Compose-key sequences at the near-bottom of this file.
                       "/run/current-system/sw/bin/sleep 1 && /run/current-system/sw/bin/setxkbmap -option compose:ralt")
  cmp-seq rctrl    ;; Set the compose key to `RightAlt'
  cmp-seq-delay 5 ;; 5ms delay between each compose-key sequence press

  ;; Comment this is you want unhandled events not to be emitted
  fallthrough true

  ;; Set this to false to disable any command-execution in KMonad
  allow-cmd true
  )
#+end_src
* Source Layer
#+begin_src kbd
(defsrc
  grv  1    2    3    4    5    6    7    8    9    0    -    =    bspc
  tab  q    w    e    r    t    y    u    i    o    p    [    ]    \
  caps a    s    d    f    g    h    j    k    l    ;    '    ret
  lsft z    x    c    v    b    n    m    ,    .    /    rsft               up
  lctl lmet lalt           spc            ralt rctl                     lft rght
                                                                          down
  )
#+end_src

* Default Layer
#+begin_quote
Optional: as many layers as you please

We had already defined `num` as referring to a `(layer-toggle numbers)`. We
will get into layer-manipulation soon, but first, let's just create a second
layer that overlays a numpad under our right-hand.

To easily specify layers it is highly recommended to create an empty
`deflayer` statement as a comment at the top of your config, so you can simply
copy-paste this template. There are also various empty layer templates
available in the './keymap/template' directory.
#+end_quote

Enable the "leader" layer for the next keypress
If we release @ldr /before/ the next key, we treat the keypress as a *tap*, even if for a short period of time both keys were down.
If we release @ldr /after/ the next key, we treat it as holding

Also, if we hold the key for more than 2 seconds, treat it like we are holding the key
#+begin_src kbd
(defalias
  ldr (tap-hold-next-release 2000 (around-next (layer-toggle leader)) lmet)
  )
#+end_src

#+begin_src kbd
(deflayer qwerty
  grv  1    2    3    4    5    6    7    8    9    0    -    =    bspc
  tab  q    w    e    r    t    y    u    i    o    p    [    ]    \
  caps a    s    d    f    g    h    j    k    l    ;    '    ret
  lsft z    x    c    v    b    n    m    ,    .    /    rsft               up
  lctl @ldr lalt           spc            ralt rctl                     lft rght
                                                                          down
  )
#+end_src
* Base Leader Key
#+begin_src kbd
(defalias
  win q ;; TODO window switcher
  dsc d ;; TODO discord
  bri b ;; TODO brightness
  vol v ;; TODO volume layer
  trm t ;; TODO terminal scratchpads
  run r ;; TODO run layer
  pro p ;; TODO prompt
  age a ;; TODO agenda
  pre o ;; TODO open preset
  lld \\ ;; TODO local leader key
  )
#+end_src

#+begin_src kbd
(deflayer leader
  XX   XX   XX   XX   XX   XX   XX   XX   XX   XX   XX   XX   XX   XX
  XX   @win XX   XX   @run XX   XX   XX   XX   XX   @pro XX   XX   XX
  XX   @age XX   @dsc XX   XX   XX   XX   XX   XX   XX   XX   XX
  XX   XX   XX   XX   @vol @bri XX   XX   XX   XX   XX   XX                 XX
  XX   lmet XX             XX             XX   XX                        XX  XX
                                                                           XX
  )
#+end_src
