#+TITLE: Logitech Keyboard Configuration
#+PROPERTY: header-args :tangle yes

* Layer Templates
#+PROPERTY: header-args :tangle no
** Passthrough
#+begin_example kbd
(deflayer layer-name
  _    _    _    _    _    _    _    _    _    _    _    _    _    _
  _    _    _    _    _    _    _    _    _    _    _    _    _    _
  _    _    _    _    _    _    _    _    _    _    _    _    _
  _    _    _    _    _    _    _    _    _    _    _    _                  _
  _    _    _              _              _    _    _                    _   _
                                                                           _
  )
#+end_src
** Inclusive
#+begin_example kbd
(deflayer layer-name
  grv  1    2    3    4    5    6    7    8    9    0    -    =    bspc
  tab  q    w    e    r    t    y    u    i    o    p    [    ]    \
  caps a    s    d    f    g    h    j    k    l    ;    '    ret
  lsft z    x    c    v    b    n    m    ,    .    /    rsft               up
  lctl lmet lalt           spc            ralt rctl                     lft rght
                                                                          down
  )
#+end_src
* Configuration
#+begin_src kbd
(defcfg
  ;; For Linux
  input  (device-file "/dev/input/by-id/usb-Logitech_USB_Receiver-if02-event-kbd")
  output (uinput-sink "Logitech KMonad Output"
                       ;; To understand the importance of the following line, see the section on
                       ;; Compose-key sequences at the near-bottom of this file.
                       "/run/current-system/sw/bin/sleep 1 && /run/current-system/sw/bin/setxkbmap -option compose:ralt")
  cmp-seq rctrl    ;; Set the compose key to `RightAlt'
  cmp-seq-delay 5 ;; 5ms delay between each compose-key sequence press

  ;; Comment this is you want unhandled events not to be emitted
  fallthrough true

  ;; Set this to false to disable any command-execution in KMonad
  allow-cmd true
  )
#+end_src
* Source Layer
#+begin_src kbd
(defsrc
  grv  1    2    3    4    5    6    7    8    9    0    -    =    bspc
  tab  q    w    e    r    t    y    u    i    o    p    [    ]    \
  caps a    s    d    f    g    h    j    k    l    ;    '    ret
  lsft z    x    c    v    b    n    m    ,    .    /    rsft               up
  lctl lmet lalt           spc            ralt rctl                     lft rght
                                                                          down
  )
#+end_src

* Default Layer
#+begin_quote
Optional: as many layers as you please

We had already defined `num` as referring to a `(layer-toggle numbers)`. We
will get into layer-manipulation soon, but first, let's just create a second
layer that overlays a numpad under our right-hand.

To easily specify layers it is highly recommended to create an empty
`deflayer` statement as a comment at the top of your config, so you can simply
copy-paste this template. There are also various empty layer templates
available in the './keymap/template' directory.
#+end_quote

Enable the "leader" layer for the next keypress
If we release @ldr /before/ the next key, we treat the keypress as a *tap*, even if for a short period of time both keys were down.
If we release @ldr /after/ the next key, we treat it as holding

Also, if we hold the key for more than 2 seconds, treat it like we are holding the key

#+begin_src kbd
(deflayer qwerty
  grv  1    2    3    4    5    6    7    8    9    0    -    =    bspc
  tab  q    w    e    r    t    y    u    i    o    p    [    ]    \
  caps a    s    d    f    g    h    j    k    l    ;    '    ret
  lsft z    x    c    v    b    n    m    ,    .    /    rsft               up
  lctl lmet lalt           spc            ralt rctl                     lft rght
                                                                          down
  )
#+end_src
